### ISSUE TITLE
Docker for rapid deployment and testing

### ISSUE THREAD

**Issue by relaxibus** [stefanor/peplink-stats-to-influxdb#1]
Hi Stefano (are you Italian, I'm),

I'm interested in your work as it is long time I had in mind to use Grafana to monitor remotely Peplink routers installed on drones.

May we have a chat?

**Comment by stefanor** [comment]
I'm an Italian, but I'm afraid I don't speak Italian, I'm only fluent in English.

Sure, happy to chat

**Comment by relaxibus** [comment]
Hi Stefano, thanks for your replay. Do your API implementation covers most of the router API for MAX? Do you offer a ready to go Docker? Do you have a contact email?

**Comment by stefanor** [comment]
> Do your API implementation covers most of the router API for MAX?

No, it only covers the bits I needed for the data that interests me on my sailboat. Most of that is from the documented APIs, some of it is from undocumented APIs that the web interface is using.

> Do you offer a ready to go Docker?

Nope, not using docker in my setup. But I'll take patches.

> Do you have a contact email?

In the license section of the README.md

**Comment by relaxibus** [comment]
Oh, you’re a sailer? We made SATCOM Iridium routers mainly for sailers :-)
Will check the readme file, thanks!
Enjoy your sailing trips :-)
