### ISSUE TITLE
Help please

### ISSUE THREAD

**Issue by eeegs** [stefanor/peplink-stats-to-influxdb#2]
Hi,
My Python is not up to speed, so I am having trouble dockerising this.  I have copied your peplink_influxdb folder into ./app

The container runs, but with the following error:

`/usr/local/bin/python3: No module named app/peplink_influxdb`

is '-m app/peplink_influxdb' still the correct command for python3?

Regards,

Scott

**Comment by stefanor** [comment]
`-m` takes a module name, so it is just `peplink_influxdb`. The `PYTHONPATH` or working-directory of the process should be the `app` directory.

**Comment by eeegs** [comment]
I'm being dumber than usual.  I have set the working directory, but...

Can you see anything wrong with this dockerfile:

FROM python:3.9
COPY ./peplink_influxdb/ /app/
COPY ./config/peplink/config.ini /app/
WORKDIR /app/

CMD ["python", "-m peplink_influxdb"]

**Comment by stefanor** [comment]
You'll also need `peplink-api` and `dateutil` to be installed. Install with pip, probably?

**Comment by stefanor** [comment]
@eeegs: All good? Can we close this?
